# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
 name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2 # Step to check out the code
    - name: Set up Python
      uses: actions/setup-python@v2 # Step to set up Python on Window
      with:
        python-version: '3.x' # Specify the Python version (e.g., 3.8, 3.9)

    - name: Install dependencies  # Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Flask flake8 pytest

    - name: Lint with Flake8
      run: flake8 test_app.py

    - name: Run unit tests
      run: python test_app.py
